### ISSUE TITLE
Code review findings - submit should also confirm + few other minor suggestions

### ISSUE THREAD

**Issue by krebernisak** [eqlabs/starknet-multisig#44]
Hi Equilibrium team 👋 

Internally, Chainlink and ShardLabs teams have reviewed the current multisig codebase and we'll present our findings in this GH Issue. No critical findings surfaced, one UX optimisation that we'd like to have and few other minor suggestions (inconsistencies or code style).

1. `submit_transaction` should also confirm transaction, as `onlySigner` is allowed. This would avoid the need to invoke a subsequent `confirm_transaction` from the same signer. Serum on Solana also implements it like [this](https://github.com/coral-xyz/multisig/blob/master/programs/multisig/src/lib.rs#L72). (**medium - functional**)
2. Event names mix present and past tense, e.g. `ConfirmTransaction` vs `SignersSet` (**minor - API**). We suggest past tense should be used for events, as do these resources:
    a. https://twitter.com/james_zaki/status/1323763725145239552
    b. https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/GUIDELINES.md#solidity-code
3. `with_attr error_message("No direct invocations allowed"):` is slightly confusing ([LOC here](https://github.com/eqlabs/starknet-multisig/blob/main/contracts/contracts/Multisig.cairo#L224)). A better error message would be something like "Access denied - only multisig". (**minor - API**)
4. `_get_signers`, `_get_transaction_calldata`, and `_set_transaction_calldata` functions should be considered to be renamed with an `_range` suffix , as to be consistent with other `_range` fn names. (**minor - code style inconsistency**)
5. Function signature style inconsistent at [Multisig.cairo#L208](https://github.com/eqlabs/starknet-multisig/blob/main/contracts/contracts/Multisig.cairo#L208). (**minor - code style inconsistency**)
6. In Multisig.test.ts there is some [mixing of camelCase](https://github.com/eqlabs/starknet-multisig/blob/16dbbdbbcbc152a43f29b9d37b7f63aad3348c48/contracts/test/Multisig.test.ts#L87) [& snake_case](https://github.com/eqlabs/starknet-multisig/blob/16dbbdbbcbc152a43f29b9d37b7f63aad3348c48/contracts/test/Multisig.test.ts#L159). To improve TS readability we  suggest using camelCase throughout the codebase (TS). (**minor - code style inconsistency**)

Hope this helps prepare the codebase for an third-party audit 🙌 

Thank you!

**Comment by microbecode** [comment]
Hi @krebernisak 

Thanks for the go-through and the descriptive list. Here are my comments:

1. If I'm thinking this right, account contract multicall can take care of this. So I think this shouldn't be implemented at the multisig contract level.
2. Good find, I agree
3. Hmm, why do you find this confusing? For me, the term "only multisig" is more confusing, since it doesn't say much about what only multisig can do. A direct invocation is when someone calls a function directly, when it should be called through the multisig, and that's what is not allowed.
4. Ok
5. Can you elaborate on this? If you mean that the parameters are on the same line, it's just about the prettier - it simply fits in the same line so it's kept there.
6. I agree

**Comment by microbecode** [comment]
I now created three PRs to fix points 2, 4 and 6: https://github.com/eqlabs/starknet-multisig/pull/46 https://github.com/eqlabs/starknet-multisig/pull/48 https://github.com/eqlabs/starknet-multisig/pull/49

**Comment by JaniAnttonen** [comment]
Didn't want to open a new issue for this, but I have a slight annoyance with a naming too; the member `threshold` of the struct `Transaction` is a bit misleading, as it means the number of approvals the transaction has gotten, instead of the threshold that needs to be met. `approvals` or `num_approvals` would be better IMO. 🤔

**Comment by microbecode** [comment]
Excellent find @JaniAnttonen . I changed it to "confirmations", since that's the used terminology throughout the contract. PR here:  https://github.com/eqlabs/starknet-multisig/pull/53

**Comment by krebernisak** [comment]
@microbecode thanks for the already applied fixes 🙌  Let me comment on the open items:

> 1. If I'm thinking this right, account contract multicall can take care of this. So I think this shouldn't be implemented at the multisig contract level.

Yes this is true. A multicall could be used or a user could make two subsequent transactions. But, both of these options require more effort on the user side. My question is why? 

What would be the specific use case for decoupling submit and confirm actions like this? I'd appreciate an example here.

Also, if there is a specific use case, is this use case something that an average user will often use, or an exception?

My thinking is that the usual average use case is for the signer to submit a transaction, one that he agrees with (approves/confirms), so the idea is to make that workflow the default one.

> 3. Hmm, why do you find this confusing? For me, the term "only multisig" is more confusing, since it doesn't say much about what only multisig can do. A direct invocation is when someone calls a function directly, when it should be called through the multisig, and that's what is not allowed.

1. The function that is the source of this error is called `require_multisig` - it raises an error "No direct invocations allowed". So for example, why isn't the function name following that logic and named as `require_no_direct_invocations`?
2. AFAIK, from reading StarkNet resources, the concept of a "direct invocation" in this domain means not using the account contract (something that will be deprecated soon): https://docs.starknet.io/docs/CLI/commands/#starknet-invoke

> Today, interaction with StarkNet may be done either via account or by a direct call. The signature argument can only be provided in the case of a direct call, since otherwise providing the signature is the responsibility of the account module. To use an account you must specify wallet_name, otherwise a direct call will be used (you may also explicitly perform a direct call by adding --no_wallet to the command). Note that in the future direct calls will be deprecated and the only way to interact with the system would be through accounts.

So in this context the message "No direct invocations allowed" means I need to use an account to sign a transaction. But if one would use an account, it would still fail with the same message. If someone would use another contract as a proxy (not directly from the account), it would still fail with the same message.

This is a minor thing, but I do see it as a confusing error message.

> 5. Can you elaborate on this? If you mean that the parameters are on the same line, it's just about the prettier - it simply fits in the same line so it's kept there.

👍

**Comment by microbecode** [comment]
Thanks @krebernisak for the comments!

About point 1: As I see it, contracts should be as simple as possible. The only exception is when keeping them simple leads into more transactions from users (a huge UX and cost issue) - that's why we have some of the "do A and B" function in the contract currently.

Users will not be crafting these transactions by themselves. They always use some UI. So the UI has to craft the transaction anyway, and at that point there is no big difference whether it creates a multicall or a single call

In general I also prefer for the contract to not do 'extra' things under the hood. It's a straightforward approach to have separate functions for each of the phases. At that point it's up to the UI to decide whether it wants to do multiple things or just one.

I would argue to keep the functionality as it is simply because of contract complexity, but here's a possible use case: user creates a transaction in advance for something, but isn't yet sure whether even he wants to have it executed, so he doesn't want to confirm it - the tx is there waiting for something else to happen (a decision, perhaps).

Yes, I agree that usually user wants to confirm the transaction in the same transaction, but that can be done by multicall.

About point 3: Ah now I see what you mean. Thanks for the explanation :) Changed in PR: https://github.com/eqlabs/starknet-multisig/pull/55

**Comment by microbecode** [comment]
The PR has been merged and a new version (0.2.2) has been published.

Can we close this issue?

**Comment by krebernisak** [comment]
Thank you, @microbecode. 

We should be good to go here 🙌
